#!/usr/bin/env python3
"""Produce a UTF-8 QA summary verifying each 第N篇 block equals framework file."""
from pathlib import Path
import re
ROOT=Path(__file__).resolve().parent.parent
BOOK=ROOT / 'book' / '1208.2025.newbook.update.md'
FRAME=ROOT / 'framework'
out=ROOT / 'tools' / 'reports' / 'insert_qa_2025-12-18.md'
book_text=BOOK.read_text(encoding='utf-8')
lines=[]
lines.append('# QA Report: Framework insertion verification\n')
lines.append('Generated by tools/qa_summary.py\n')
lines.append('\n## Per-篇 Summary\n')
lines.append('| 篇 | Status | framework lines | book block lines | markers present | 12.16建议 (framework/book) | placeholders |')
lines.append('|---:|---|---:|---:|---:|---:|---|')
for i in range(1,8):
    # find framework file
    fr_list=list(FRAME.glob(f'第{i}篇*.md'))
    if not fr_list:
        status='missing_framework_file'
        lines.append(f'| 第{i}篇 | {status} | - | - | - | - | - |')
        continue
    fr=fr_list[0]
    fr_text=fr.read_text(encoding='utf-8')
    n_fr=len(fr_text.splitlines())
    bm=re.compile(r"<!--\s*BEGIN\s*第"+str(i)+r"篇\s*-->")
    em=re.compile(r"<!--\s*END\s*第"+str(i)+r"篇\s*-->")
    mb=bm.search(book_text)
    me=em.search(book_text)
    markers_present=bool(mb and me)
    block=''
    if markers_present:
        block=book_text[mb.end():me.start()]
    normalized=lambda t: '\n'.join([ln.rstrip() for ln in t.replace('\r\n','\n').split('\n')]).strip()
    norm_fr=normalized(fr_text)
    norm_block=normalized(block)
    identical = (norm_fr==norm_block)
    n_block=len(block.splitlines()) if block else 0
    suggests_fr=len(re.findall(r'12\.16建议', fr_text))
    suggests_block=len(re.findall(r'12\.16建议', block))
    placeholders=[]
    if re.search(r'（余下|余下', block): placeholders.append('ellipsis')
    if 'truncated' in block.lower(): placeholders.append('truncated')
    if '<THE FULL CONTENT' in block: placeholders.append('completion-note')
    status = 'identical' if identical else ('differs' if markers_present else 'missing block')
    lines.append(f'| 第{i}篇 | {status} | {n_fr} | {n_block} | {markers_present} | {suggests_fr}/{suggests_block} | {",".join(placeholders) or "-"} |')
# write details
lines.append('\n\n## Notes\n')
lines.append('- All framework files were read from `framework/` and inserted into `book/1208.2025.newbook.update.md` between matching <!-- BEGIN 第N篇 --> / <!-- END 第N篇 --> markers.\n')
lines.append('- "identical" means normalized text matches exactly; "differs" means mismatch found.\n')
out.write_text('\n'.join(lines),encoding='utf-8')
print('QA summary written to', out)
