*.sink.prometheus.class=org.apache.spark.metrics.sink.PrometheusSink
*.sink.prometheus.period=10
*.sink.prometheus.unit=seconds
*.sink.prometheus.port=8090

master.source.jvm.class=org.apache.spark.metrics.source.JvmSource
worker.source.jvm.class=org.apache.spark.metrics.source.JvmSource
driver.source.jvm.class=org.apache.spark.metrics.source.JvmSource
executor.source.jvm.class=org.apache.spark.metrics.source.JvmSource

driver.source.BlockManagerSource.class=org.apache.spark.metrics.source.BlockManagerSource
executor.source.BlockManagerSource.class=org.apache.spark.metrics.source.BlockManagerSource

driver.source.DAGSchedulerSource.class=org.apache.spark.metrics.source.DAGSchedulerSource
